# Указываем версию синтаксиса файла
version: '3.8'

# Блок, в котором описываются все наши сервисы (контейнеры)
services:
  # Даем имя нашему первому сервису - "web"
  web:
    # Инструкция по сборке: "собери образ из Dockerfile в текущей папке (.)"
    build: .
    # Команда, которая запустится при старте контейнера
    command: python manage.py runserver 0.0.0.0:8000
    # Проброс папки с кодом с нашего компьютера внутрь контейнера
    volumes:
      - .:/app
    # Проброс портов: соединяем порт 8000 нашего ПК с портом 8000 контейнера
    ports:
      - "8000:8000"