# Generated by Django 5.2.6 on 2025-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Upload image cover",
                null=True,
                upload_to="locallibrary/media",
            ),
        ),
    ]
